movieproject/movieapp/urls.py
from . import views
from django.urls import path

app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movies,name='add_movies'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='film')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from .models import Movie


# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,"index.html",context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movies(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        messages.info(request,'MOVIE ADDED SUCCESSFULLY')
        return redirect('/')
    return render(request,'add_movies.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add_movies.html
{% load static %}
<!--<!DOCTYPE html>-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'style.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .registration-container {
            width: 300px;
            margin: 100px auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #E3E6E3;
        }

        .registration-container label {
            display: block;
            margin-bottom: 5px;
        }

        .registration-container input[type="text"],
        .registration-container input[type="file"] {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        .registration-container input[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            border: none;
            border-radius: 3px;
            color: #fff;
            cursor: pointer;
        }

        .registration-container input[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
<nav class="navbar" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1"> ONLINE MOVIES STORE</span>
  </div>
</nav>
<div class="registration-container">
    <h2 align="center" style="font-family: Georgia, serif;">Add Movies</h2>
    <div class="row ">
        <div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                    <input type="text" name="name" placeholder="Enter The Movie Name" required>
                </div>
                <div>
                    <input type="text" name="desc" placeholder="Enter About Movie" required>
                </div>
                <div>
                    <input type="text" name="year" placeholder="Enter The Year" >
                </div>
                <div>
                    <input type="file" name="img"  >
                </div>
                <div>
                    <input type="submit">
                </div>
            </form>
        </div>

    </div>

</div>
</body>
</html>

movieproject/templates/base.html
{% load static %}
<!--<!DOCTYPE html>-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar" style="background-color: #e3f2fd;">
  <div class="container-fluid p-3">
    <h2 class="navbar-brand mb-3 h1 pt-3" style="font-family: Georgia, serif;" ><strong> ONLINE MOVIES STORE</strong></h2>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<center>
<form method="post" >
    {% csrf_token %}
    Are You Sure Want To Delete?<br>
    <input type="submit">
</form>
</center>
{% endblock %}

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid">
    <div class="row mt-3">
        <div class="col-md-4 ">
           <img src="{{movie.img.url}}" width="400px" height="400px">
        </div>
        <div class="col-md-8">
            <h2>{{movie.name}}</h2><br>
            <h3>{{movie.year}}</h3><br>
            <h4>{{movie.desc}}</h4><br>

            <!--now this is a link we need to set it has a button so give class="btn btn-danger"-->
            <a class="btn btn-primary" href="{% url 'movieapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
<!--    the form we can see here is from the function update in dict we gave form and movie that form is this-->
    {{form.as_p}}
    <input type="submit">
</form>
</div>
{% endblock %}

movieproject/templates/index.html
{% load static %}
<!--<!DOCTYPE html>-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar" style="background-color: #e3f2fd;">
  <div class="container-fluid p-3">
    <h2 class="navbar-brand mb-3 h1 pt-3" style="font-family: Georgia, serif;" ><strong> ONLINE MOVIES STORE</strong></h2>
      <a style="float: right;" class="btn btn-outline-secondary" href="{% url 'movieapp:add_movies' %}">ADD MOVIES</a>
  </div>
</nav>
<div class="container-fluid">
    <div class="row ml-5">
        {% for i in movie_list %}
        <div class="col-md-3  mt-5 rounded ">
           <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100px" height="300px">
                    <div class="card-body">
                        <h2 class="card-title">{{i.name}}</h2>
                        <h4 class="card-text">{{i.year}}</h4>
                        <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Get Details</a>
                    </div>
           </div>
        </div>
        {% endfor %}
    </div>
</div>




</body>
</html>